# Generated by Django 4.1.7 on 2023-03-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appInicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Nombre')),
                ('rut', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='RUT')),
                ('giro', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Giro Comercial')),
                ('direccion', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Teléfono')),
                ('correo', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Correo Electronico')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('registroFechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appInicio.comuna', verbose_name='Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appInicio.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
