# Generated by Django 4.1.7 on 2023-03-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Descripcion')),
                ('m2', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Metros Cuadrados')),
                ('m3', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Metros Cubicos')),
                ('uf', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='UF')),
                ('valorNeto', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Valor Neto')),
                ('valorIva', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Valor IVA')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('registroFechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de\xa0Modificación')),
            ],
        ),
    ]
