# Generated by Django 4.1.7 on 2023-03-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCamara', '0002_alter_camara_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='guia',
            field=models.FileField(blank=True, default=None, null=True, upload_to='guias/camaras/'),
        ),
    ]
