# Generated by Django 4.1.7 on 2023-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCamara', '0003_camara_guia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camara',
            name='guia',
        ),
        migrations.AddField(
            model_name='camara',
            name='ficha',
            field=models.FileField(blank=True, default=None, null=True, upload_to='guias/camaras/', verbose_name='Ficha'),
        ),
    ]
