# Generated by Django 4.1.7 on 2023-03-23 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCliente', '0001_initial'),
        ('appCamara', '0004_remove_camara_guia_camara_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Descripcion')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('registroFechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de\xa0Modificación')),
            ],
            options={
                'verbose_name': 'Tipo De Camara',
                'verbose_name_plural': 'Tipos de Camaras',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Descripcion')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('registroFechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de\xa0Modificación')),
            ],
            options={
                'verbose_name': 'Tipo De Pago',
                'verbose_name_plural': 'Tipos de Pagos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Observación')),
                ('correlativo', models.IntegerField(blank=True, default=None, null=True, verbose_name='Correlativo')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Descuento')),
                ('neto', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Valor Neto')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Valor IVA')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Valor Total')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('registroFechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de\xa0Modificación')),
                ('camara', models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appCamara.camara', verbose_name='Camara')),
                ('cliente', models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appCliente.cliente', verbose_name='Cliente')),
                ('tipo', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appCamara.tipopago', verbose_name='Condición de Pago')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['correlativo'],
            },
        ),
        migrations.AddField(
            model_name='camara',
            name='tipo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appCamara.tipocamara', verbose_name='Tipo de Camara'),
        ),
    ]
