# Generated by Django 4.1.7 on 2023-03-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCamara', '0005_tipocamara_tipopago_cotizacion_camara_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='subNeto',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Valor SubNeto'),
        ),
        migrations.AlterField(
            model_name='camara',
            name='m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Metros Cuadrados'),
        ),
        migrations.AlterField(
            model_name='camara',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Metros Cubicos'),
        ),
        migrations.AlterField(
            model_name='camara',
            name='uf',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='camara',
            name='valorIva',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Valor IVA'),
        ),
        migrations.AlterField(
            model_name='camara',
            name='valorNeto',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Valor Neto'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Valor IVA'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Valor Neto'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Valor Total'),
        ),
    ]
