# Generated by Django 4.1.7 on 2023-05-18 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCamara', '0008_remove_cotizacion_camara_cotizacion_camara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='camara',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='comuna',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='giro',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Giro Comercial'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='intalacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Valor Intalación'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='rut',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sennor',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Señor'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='transporte',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Valor Transporte'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Condición de Pago'),
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Item')),
                ('codigo', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Descripcion')),
                ('cantidad', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cantidad')),
                ('precioUnitario', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Precio Unitario')),
                ('descuento', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Descuento')),
                ('valor', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Valor')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appCamara.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de la Cotización',
                'ordering': ['id'],
            },
        ),
    ]
