# Generated by Django 4.1.7 on 2023-03-12 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=5, verbose_name='Código ISO 3166-2')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Región')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('registroFechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Provincia')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('registroFechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appInicio.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Comuna')),
                ('cut', models.PositiveSmallIntegerField(unique=True, verbose_name='Código Único Territorial')),
                ('area', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Área (km2)')),
                ('poblacion', models.PositiveIntegerField(verbose_name='Población (2017)')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('registroFechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appInicio.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['nombre'],
            },
        ),
    ]
