# Generated by Django 4.1.7 on 2023-03-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='km',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Kilometro'),
        ),
    ]
